# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHe4_U_NfB0laIPkRn2aV_4EIVpsymJz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, ConfusionMatrixDisplay

print("1. Загрузка данных Pima Indians Diabetes")

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
column_names = ['pregnant', 'glucose', 'pressure', 'skin_thickness', 'insulin', 'bmi', 'pedigree', 'age', 'outcome']
df_diabetes = pd.read_csv(url, names=column_names)

print(f"Размер данных: {df_diabetes.shape}")

print("\n2. Подготовка данных для модели")

# Разделение на признаки и целевую переменную
X = df_diabetes.drop('outcome', axis=1)
y = df_diabetes['outcome']

print(f"Признаки: {X.columns.tolist()}")
print(f"Целевая переменная: outcome (0 - нет диабета, 1 - диабет)")
print(f"Размер X: {X.shape}")

# Разделение на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y,  # Сохраняем распределение классов
    shuffle=True
)

# Стандартизация признаков
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\n3. Обучение модели логистической регрессии")
model = LogisticRegression(random_state=42, max_iter=1000)
model.fit(X_train_scaled, y_train)

print("\n4. Оценка модели...")
y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print(f"Accuracy:  {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall:    {recall:.3f}")

print("\n5. Матрица ошибок")
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

print(f"\nМатрица ошибок:")
print(f"TN: {tn} | FP: {fp}")
print(f"FN: {fn} | TP: {tp}")

print(f"\nАнализ ошибок:")
print(f"Ложноположительные (FP): {fp} пациентов")
print(f"  - Здоровым ошибочно поставили диабет")
print(f"Ложноотрицательные (FN): {fn} пациентов")
print(f"  - Больным диабетом ошибочно сказали, что здоровы")

# Визуализация матрицы ошибок
plt.figure(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Нет диабета', 'Диабет'])
disp.plot(cmap='Blues', values_format='d')
plt.title('Матрица ошибок')
plt.tight_layout()
plt.show()