# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfbGKY_im_w9eLK8lpVTZ1sjsr44jvLK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

#загрузка данных
print("1. Загрузка данных")
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']
df_auto = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?')

#просмотр данных
print(df_auto.head())
print(df_auto.info())

#заменяем пропуски медианой
print("\n2. Обработка пропусков")
print("Пропуски в horsepower:", df_auto['horsepower'].isnull().sum())
imputer = SimpleImputer(strategy='median')
df_auto['horsepower'] = imputer.fit_transform(df_auto[['horsepower']])

print("\n3. Подготовка данных для модели")

# Выбор признаков и целевой переменной
X = df_auto[['cylinders', 'horsepower', 'weight']]
y = df_auto['mpg']

print(f"Признаки: {X.columns.tolist()}")
print(f"Целевая переменная: mpg")
print(f"Размер X: {X.shape}")

# Разделение на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)
print(f"Обучающая выборка: {X_train.shape[0]} samples")
print(f"Тестовая выборка: {X_test.shape[0]} samples")

print("\n4. Обучение модели линейной регрессии")

model = LinearRegression()
model.fit(X_train, y_train)

print(f"Коэффициенты: {model.coef_}")
print(f"Intercept: {model.intercept_:.2f}")

print("\n5. Оценка модели")

# Предсказания
y_pred = model.predict(X_test)

# Метрики
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE (Mean Squared Error): {mse:.2f}")
print(f"R² (Coefficient of Determination): {r2:.2f}")

print("\n6. Визуализация зависимости mpg от horsepower")

plt.figure(figsize=(10, 6))

# Диаграмма рассеяния
plt.scatter(X_test['horsepower'], y_test, alpha=0.7, color='blue', label='Фактические значения')

# Линия регрессии
# Для визуализации используем предсказания только по horsepower
horsepower_range = np.linspace(X_test['horsepower'].min(), X_test['horsepower'].max(), 100)
# Создаем фиктивные данные для предсказания (средние значения других признаков)
cylinders_mean = X_test['cylinders'].mean()
weight_mean = X_test['weight'].mean()

# Предсказания для линии регрессии
line_data = pd.DataFrame({
    'cylinders': [cylinders_mean] * 100,
    'horsepower': horsepower_range,
    'weight': [weight_mean] * 100
})
regression_line = model.predict(line_data)

plt.plot(horsepower_range, regression_line, color='red', linewidth=2, label='Линия регрессии')

plt.xlabel('Лошадиные силы (horsepower)')
plt.ylabel('Мили на галлон (mpg)')
plt.title('Зависимость расхода топлива (mpg) от мощности двигателя (horsepower)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()